-- MySQL Script generated by MySQL Workbench
-- Wed Sep 23 08:12:19 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema klingogbang
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `klingogbang` ;

-- -----------------------------------------------------
-- Schema klingogbang
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `klingogbang` DEFAULT CHARACTER SET utf8 ;
USE `klingogbang` ;

-- -----------------------------------------------------
-- Table `klingogbang`.`Author`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `klingogbang`.`Author` ;

CREATE TABLE IF NOT EXISTS `klingogbang`.`Author` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `created` DATETIME NULL DEFAULT NULL,
  `affected` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `klingogbang`.`Entry`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `klingogbang`.`Entry` ;

CREATE TABLE IF NOT EXISTS `klingogbang`.`Entry` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `from` DATE NOT NULL,
  `to` DATE NULL DEFAULT NULL,
  `created` DATETIME NULL DEFAULT NULL,
  `affected` DATETIME NULL DEFAULT NULL,
  `type` VARCHAR(4) NOT NULL DEFAULT 'show',
  `body_is` TEXT NULL DEFAULT NULL,
  `body_en` TEXT NULL DEFAULT NULL,
  `orientation` CHAR(1) NOT NULL DEFAULT 'v',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `klingogbang`.`Entry_has_Author`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `klingogbang`.`Entry_has_Author` ;

CREATE TABLE IF NOT EXISTS `klingogbang`.`Entry_has_Author` (
  `entry_id` INT(11) NOT NULL,
  `author_id` INT(11) NOT NULL,
  `order` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`entry_id`, `author_id`),
  INDEX `fk_Entry_has_Author_Author` (`author_id` ASC) VISIBLE,
  CONSTRAINT `fk_Entry_has_Author_Author`
    FOREIGN KEY (`author_id`)
    REFERENCES `klingogbang`.`Author` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Entry_has_Author_Entry`
    FOREIGN KEY (`entry_id`)
    REFERENCES `klingogbang`.`Entry` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `klingogbang`.`Image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `klingogbang`.`Image` ;

CREATE TABLE IF NOT EXISTS `klingogbang`.`Image` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `size` INT(11) NOT NULL DEFAULT '0',
  `width` INT(11) NOT NULL DEFAULT '0',
  `height` INT(11) NOT NULL DEFAULT '0',
  `created` DATETIME NULL DEFAULT NULL,
  `affected` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `klingogbang`.`Entry_has_Image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `klingogbang`.`Entry_has_Image` ;

CREATE TABLE IF NOT EXISTS `klingogbang`.`Entry_has_Image` (
  `image_id` INT(11) NOT NULL,
  `entry_id` INT(11) NOT NULL,
  `order` INT(11) NOT NULL DEFAULT '0',
  `type` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`image_id`, `entry_id`),
  INDEX `fk_Entry_has_Poster_Item` (`entry_id` ASC) VISIBLE,
  CONSTRAINT `fk_Entry_has_Poster_Image`
    FOREIGN KEY (`image_id`)
    REFERENCES `klingogbang`.`Image` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Entry_has_Poster_Item`
    FOREIGN KEY (`entry_id`)
    REFERENCES `klingogbang`.`Entry` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `klingogbang`.`Inventory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `klingogbang`.`Inventory` ;

CREATE TABLE IF NOT EXISTS `klingogbang`.`Inventory` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `created` DATETIME NULL DEFAULT NULL,
  `affected` DATETIME NULL DEFAULT NULL,
  `body_is` TEXT NULL DEFAULT NULL,
  `body_en` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `klingogbang`.`Inventory_has_Image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `klingogbang`.`Inventory_has_Image` ;

CREATE TABLE IF NOT EXISTS `klingogbang`.`Inventory_has_Image` (
  `image_id` INT(11) NOT NULL,
  `inventory_id` INT(11) NOT NULL,
  `order` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`image_id`, `inventory_id`),
  INDEX `fk_Inventory_has_Poster_Item` (`inventory_id` ASC) VISIBLE,
  CONSTRAINT `fk_Inventory_has_Poster_Image`
    FOREIGN KEY (`image_id`)
    REFERENCES `klingogbang`.`Image` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Inventory_has_Poster_Item`
    FOREIGN KEY (`inventory_id`)
    REFERENCES `klingogbang`.`Inventory` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `klingogbang`.`Manifesto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `klingogbang`.`Manifesto` ;

CREATE TABLE IF NOT EXISTS `klingogbang`.`Manifesto` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(10) NOT NULL,
  `body_is` TEXT NULL DEFAULT NULL,
  `body_en` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `type` (`type` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `klingogbang`.`Manifesto_has_Image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `klingogbang`.`Manifesto_has_Image` ;

CREATE TABLE IF NOT EXISTS `klingogbang`.`Manifesto_has_Image` (
  `image_id` INT(11) NOT NULL,
  `entry_id` INT(11) NOT NULL,
  `order` INT(11) NOT NULL DEFAULT '0',
  `type` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`image_id`, `entry_id`),
  INDEX `fk_Entry_has_Poster_Item` (`entry_id` ASC) VISIBLE,
  CONSTRAINT `fk_Manifesto_has_Poster_Image`
    FOREIGN KEY (`image_id`)
    REFERENCES `klingogbang`.`Image` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Manifesto_has_Poster_Item`
    FOREIGN KEY (`entry_id`)
    REFERENCES `klingogbang`.`Manifesto` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `klingogbang`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `klingogbang`.`User` ;

CREATE TABLE IF NOT EXISTS `klingogbang`.`User` (
  `id` CHAR(38) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `type` TINYINT(4) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
